### ISSUE TITLE
small images on articles

### ISSUE THREAD

**Issue by 4agoodcause** [4agoodcause/4aGoodWebsite#10]
Need a way to left or right align small images on figure tag on blog articles. 

example:
http://2015.4agoodcause.com/blog/article-Client-spotlight-Southwest-Christian-Care.aspx

**Comment by bradsawicki** [comment]
You're going to run into issues on mobile screens aligning images of this size. Normally, I would set up a set of classes to left and right align embedded images that would go to full width on mobile, but this image to far too small. I can set up a left/right align class that keeps images aligned on mobile, but as soon as an aligned image reaches the full width of the screen, there will be some wonky left/right margin issues. Ideally, we don't want to be posting images of this low of quality on the site, so do you have access to a larger, high quality image?

Here are the classes I set up:
https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/css/styles.css#L2164-L2176

**Comment by 4agoodcause** [comment]
Thanks. I'll try to avoid this type of image in the future.
