### ISSUE TITLE
Footer Logo

### ISSUE THREAD

**Issue by bradsawicki** [4agoodcause/4aGoodWebsite#11]
Ronald,
I noticed a bug with the footer logo. See the attached. The svg file you're using is different from the one I pushed up to the repo, so replace it with this one:

https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/images/logo-white.svg

Also, the rest of the site's footer logo is using the png version, so replace that when you get a chance, as well. Thanks!
<img width="618" alt="screen shot 2016-01-13 at 4 15 13 pm" src="https://cloud.githubusercontent.com/assets/849704/12309650/79801520-ba11-11e5-9f60-c3f18c2b67bf.png">

**Comment by 4agoodcause** [comment]
Thanks. I replaced the file. Don't think it solved the bug though.

Ronald

On Wed, Jan 13, 2016 at 5:19 PM, Brad Sawicki notifications@github.com
wrote:

> Ronald,
> I noticed a bug with the footer logo. See the attached. The svg file
> you're using is different from the one I pushed up to the repo, so replace
> it with this one:
> 
> https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/images/logo-white.svg
> 
> Also, the rest of the site's footer logo is using the png version, so
> replace that when you get a chance, as well. Thanks!
> [image: screen shot 2016-01-13 at 4 15 13 pm]
> https://cloud.githubusercontent.com/assets/849704/12309650/79801520-ba11-11e5-9f60-c3f18c2b67bf.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/4agoodcause/4aGoodWebsite/issues/11.

## 

Ronald Pruitt
4aGoodCause
770-517-5962
ronald.pruitt@4agoodcause.com
www.4aGoodCause.com

Support our good causes on Giving Tuesday:
http://4agoodcause.com/givingtuesday/

Read my blog at http://4agoodcause.com/blog

Follow me at https://twitter.com/4aGC

Ecommerce, website and mobile solutions for nonprofits, schools and
hospitals

**Comment by bradsawicki** [comment]
Ah! Sorry, it looks like the site is missing the max-width set to the logo div.

https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/css/styles.css#L2773-L2776

**Comment by 4agoodcause** [comment]
That did the trick! Thanks for looking out for us.

Ronald

On Wed, Jan 13, 2016 at 5:54 PM, Brad Sawicki notifications@github.com
wrote:

> Ah! Sorry, it looks like the site is missing the max-width set to the logo
> div.
> 
> https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/css/styles.css#L2773-L2776
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/4agoodcause/4aGoodWebsite/issues/11#issuecomment-171463249
> .

## 

Ronald Pruitt
4aGoodCause
770-517-5962
ronald.pruitt@4agoodcause.com
www.4aGoodCause.com

Support our good causes on Giving Tuesday:
http://4agoodcause.com/givingtuesday/

Read my blog at http://4agoodcause.com/blog

Follow me at https://twitter.com/4aGC

Ecommerce, website and mobile solutions for nonprofits, schools and
hospitals

**Comment by bradsawicki** [comment]
Great! No probs. Proud of the work we do together
