### ISSUE TITLE
nav mouseover

### ISSUE THREAD

**Issue by 4agoodcause** [4agoodcause/4aGoodWebsite#7]
Is there a way to lock the mouseover on the top nav when you are in that section? I could only find a setting to add the blue underline when hover. Could not find an "active" setting.

**Comment by bradsawicki** [comment]
I added active class to the nav link. Replace line 2440 with this:

https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/css/styles.css#L2440-L2445

**Comment by bradsawicki** [comment]
The lines changed when I made the form updates. Here ya go:

https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/css/styles.css#L2450-L2455

**Comment by 4agoodcause** [comment]
Works!
