### ISSUE TITLE
send button on form

### ISSUE THREAD

**Issue by 4agoodcause** [4agoodcause/4aGoodWebsite#8]
On http://2015.4agoodcause.com/request-demo.aspx - When I converted the form to my tech, the Send button is now small. Can we get it back 100% width? Plus I need a little more space, especially on mobile, between that button and the Google captcha I added above it.

**Comment by bradsawicki** [comment]
Here are the form button lines to replace:

https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/css/styles.css#L2450-L2455

And I added a bottom margin to the Captcha. Add this:

https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/css/styles.css#L764-L768

**Comment by 4agoodcause** [comment]
Looks good!
