### ISSUE TITLE
thriple screenshot image

### ISSUE THREAD

**Issue by 4agoodcause** [4agoodcause/4aGoodWebsite#9]
The triple image on http://2015.4agoodcause.com/features.aspx does not have enough color. Can I get a triple screenshot of the following alternates...
https://secure3.4agoodcause.com/save-the-manatee-club/gift.aspx?id=9
https://secure3.4agoodcause.com/project-cure/gift.aspx?id=4

**Comment by bradsawicki** [comment]
Do you want use these for all three screen shots? Or use one of each. If one of each, what order do you want them?

**Comment by 4agoodcause** [comment]
You can do it just like you did the original (attached). One page for all three. 
![browser-shots-01](https://cloud.githubusercontent.com/assets/7489942/8010487/8d57df48-0b7e-11e5-9f40-4d7b20e9202f.jpg)

**Comment by bradsawicki** [comment]
Here are the two new images:

https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/images/browser-shots-02.jpg
https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/images/browser-shots-03.jpg

The donate amount buttons don't work too well for this image. We may need to find a different page to use as a screen shot.

**Comment by 4agoodcause** [comment]
True. How about this event page?

https://secure3.4agoodcause.com/ramapo-college-foundation/register.aspx?eventid=1

**Comment by bradsawicki** [comment]
Works much better!
https://github.com/4agoodcause/4aGoodWebsite/blob/master/assets/images/browser-shots-04.jpg

**Comment by 4agoodcause** [comment]
Looks great! 

I'll let you know if I need anything else but I think I'm close to launching! 

Thanks for the great work.
